// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnJN0BVSAv3VhA7lgYfwqzu6x59Q-egJ4',
    appId: '1:911642471425:web:c16529d9b56c051118a400',
    messagingSenderId: '911642471425',
    projectId: 'library-store-ba2f3',
    authDomain: 'library-store-ba2f3.firebaseapp.com',
    storageBucket: 'library-store-ba2f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqxwliUNeYbC1UvZR2hrCo2rzu8xJTxys',
    appId: '1:911642471425:android:fd7bea4cca4aa4bc18a400',
    messagingSenderId: '911642471425',
    projectId: 'library-store-ba2f3',
    storageBucket: 'library-store-ba2f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1PStjz2Va_QEC0Li5vdE6oXer7w9yM70',
    appId: '1:911642471425:ios:8a3622383117bf5518a400',
    messagingSenderId: '911642471425',
    projectId: 'library-store-ba2f3',
    storageBucket: 'library-store-ba2f3.appspot.com',
    iosClientId: '911642471425-r9giqt111jkqqcu5dbjmis6v5ifvg0pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.libraryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1PStjz2Va_QEC0Li5vdE6oXer7w9yM70',
    appId: '1:911642471425:ios:8a3622383117bf5518a400',
    messagingSenderId: '911642471425',
    projectId: 'library-store-ba2f3',
    storageBucket: 'library-store-ba2f3.appspot.com',
    iosClientId: '911642471425-r9giqt111jkqqcu5dbjmis6v5ifvg0pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.libraryApp',
  );
}
